project:
  type: website

editor:
  render-on-save: true

website:
  title: "DigiPres.org Practices"
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - section: "Reports"
        href: reports/index.qmd
        contents: reports/*/index.qmd
      - section: "Tool Demos"
        href: tool-demos/index.qmd
        contents: tool-demos/*/index.qmd
  favicon: logo.png
  twitter-card: true
  site-url: https://digipres.org/practices/
  search: true
  repo-url: https://github.com/digipres/practices/
  repo-actions: [edit]
  navbar:
    right:
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Warning** - This is an early-stage experimental prototype! All may change! See the homepage for more information."
    type: warning
    position: above-navbar

syntax-highlighting: pygments

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
  epub: default
  pdf:
    title: pdf-title
    toc: true
    papersize: a4
    number-sections: true
    colorlinks: true