project:
  type: book

editor:
  render-on-save: true

book:
  title: "DigiPres.org"
  author: "DigiPres.org Contributors"
  date: "8/18/2021"
  chapters:
    - index.qmd
    - tool-demos/droid/index.qmd
    - about.qmd
  favicon: logo.png
  twitter-card: true
  site-url: https://digipres.org/practices/
  search: true
  repo-url: https://github.com/digipres/practices/
  repo-actions: [edit]
  downloads: [pdf, epub]
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com

#bibliography: references.bib

syntax-highlighting: pygments

format:
  html:
    theme:
      - cosmo
    css: styles.css
  pdf:
    papersize: a4
#    documentclass: scrreprt # Note that this line makes 'quarto preview' crash!?
#  epub:
#    cover-image: cover.png


