project:
  type: website

editor:
  render-on-save: true

website:
  title: "DigiPres.org"
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - section: "Tool Demos"
        href: tool-demos/index.qmd
        contents:
          - text: "DROID"
            href: tool-demos/droid/index.qmd
  favicon: logo.png
  twitter-card: true
  site-url: https://digipres.org/practices/
  search: true
  repo-url: https://github.com/digipres/practices/
  repo-actions: [edit]
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com

syntax-highlighting: pygments

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
