---
listing: 
  - id: tool-demos
    contents: "tool-demos/*/*.qmd"
    type: grid
  - id: reports
    contents: "reports/*/*.qmd"
    type: table
format:
  html: default
---
# Welcome

::: {.callout-warning}
## This site is an experimental prototype!

This is being used to explore how to host various kinds of technical documentation. The current state of this site may not reflect the final destination for all of this content!

If you have any comments or questions, please [get in touch!](mailto:andrew.jackson@dpconline.org?subject=DigiPres.org%20Practices).
::: 

Welcome to DigiPres.org Practices, a place to publish shared technical documentation on tools and processes relating to the practice of digital preservation.

This is an early experimental prototype, using the [Quarto](http://quarto.org/) publication system to combine a range of practical resources into a single reference library.

## Tool Demos

These tool demos were originally part of the [DPC Digital Preservation Handbook](https://www.dpconline.org/handbook). They are not going to be included in the next version of the handbook, so we are placing them here so they are still available and can be updated by the wider community.

:::{#tool-demos}
:::

## Reports

This section is for detailed technical reporting and analysis on digital preservation practices.

:::{#reports}
:::

## Funding & Development

The initial development of this site was funded by Yale University Library and the Digital Preservation Coalition (DPC) as part of the [Registries of Good Practice project](https://github.com/digipres/registries-of-practice-project).

Updates and additions have been funded by the [DPC Member Support programme](https://www.dpconline.org/digipres/discover-good-practice/dedicated-support-for-members).

## Get In Touch

If you have any questions, please get in touch [via the contacts and forums listed on the DigiPres.org home page](https://www.digipres.org/).

