[[main]]
name = "About"
pageRef = "about"
weight = 20
title = "Made with ❤️ by the Hugo Bootstrap Theme team"

[[main]]
identifier = "groups"
name = "Groups"
weight = 40

[[main]]
name = "All"
pageRef = "groups"
weight = 100
parent = "groups"

[[main]]
name = "Local & Regional"
pageRef = "groups/local"
weight = 20
parent = "groups"

[[social]]
  name = "GitHub"
  pre = "<svg xmlns='http://www.w3.org/2000/svg' class='feather feather-github'><use href='/hugo-bootstrap-theme/images/feather/feather-sprite.svg#github'/></svg>"
  url = "https://github.com/filipecarneiro/hugo-bootstrap-theme/"
  weight = 10
  title = "Visit the GitHub project"

[[social]]
  name = "Twitter"
  pre = "<svg xmlns='http://www.w3.org/2000/svg' class='feather feather-twitter'><use href='/hugo-bootstrap-theme/images/feather/feather-sprite.svg#twitter'/></svg>"
  url = "https://twitter.com/jfilipecarneiro/"
  weight = 20
  title = "Contact on Twitter"
